table clients_36_mois
	lineageTag: 2873060b-1093-4c7c-ba21-ba9451952dad

	column client_id
		dataType: string
		lineageTag: b815acaa-d925-4b11-8312-0aeb14debfec
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: a5b5790a-e94a-4745-a2f3-171904c4de68
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	column telephone
		dataType: string
		lineageTag: a8a84507-cbb1-449a-83ef-4933602cb9ba
		summarizeBy: none
		sourceColumn: telephone

		annotation SummarizationSetBy = Automatic

	column zone_principale
		dataType: string
		lineageTag: bdae6617-6274-4b08-9671-71e7ac60ee9d
		summarizeBy: none
		sourceColumn: zone_principale

		annotation SummarizationSetBy = Automatic

	column canal_acquisition
		dataType: string
		lineageTag: e1da72be-8212-41a9-9bc1-8d0561246f7a
		summarizeBy: none
		sourceColumn: canal_acquisition

		annotation SummarizationSetBy = Automatic

	column date_premiere_consultation
		dataType: dateTime
		formatString: Long Date
		lineageTag: 616d22fc-b08a-43e5-9a35-2d5cd2a648f2
		summarizeBy: none
		sourceColumn: date_premiere_consultation

		variation Variation
			isDefault
			relationship: 45b72f1d-7b58-4513-bf8c-3907f18cdfdd
			defaultHierarchy: LocalDateTable_95985ade-ea90-4d4a-8ad6-e86504771cc0.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column statut
		dataType: string
		lineageTag: 3eaeb524-26df-426b-9607-60bdfdfb97c1
		summarizeBy: none
		sourceColumn: statut

		annotation SummarizationSetBy = Automatic

	partition clients_36_mois = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\TheFreelanceWay\Cas pratiques\022026_Cabinet_electrolyse\clients_36_mois.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"date_premiere_consultation", type date}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

