table google_analytics_36_mois
	lineageTag: 83fae81c-662c-4523-9dc9-6a2d36646849

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e74ca32-d951-4580-8b5b-5a1199c612ea
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column source
		dataType: string
		lineageTag: 7507455a-77f9-408e-9d4a-ec31e9597992
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 7fc7749f-0e17-494d-93f2-de6c792b21d8
		summarizeBy: sum
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column users
		dataType: int64
		formatString: 0
		lineageTag: bfa68709-01cb-4054-9e7a-df8cfe956861
		summarizeBy: sum
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	partition google_analytics_36_mois = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\TheFreelanceWay\Cas pratiques\022026_Cabinet_electrolyse\02_data\google_analytics_36_mois.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"date", type date}, {"source", type text}, {"sessions", Int64.Type}, {"users", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

